version: 1.1.0.{build}
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: yf9us+MKYVHZHh/WFrrSivSPnJnjF9KFhhaZoNg9KONIBGN7CKb/JOBHoih4SIOL
  on:
    branch: master